### PR TITLE
Updating NuGet media to new logo

### PR DESCRIPTION
**Pull request by jonwchu**

### CODE REVIEW

**Comment by anangaur** [comment]
Are all files being updated? If there is some file that is no longer required, please delete those files.

**Comment by jonwchu** [comment]
All the files in the MainLogo folder has been updated... I didn't touch the "Others" folder but those look like they aren't used anymore. I can delete them all if you want.

**Comment by jonwchu** [comment]
Also, moved the .ai and .psd files into a separate folder since it was a bit strange that they were only there for the 128x128 asset

**Comment by anangaur** [comment]
Looks good thanks

**Review by anangaur — APPROVED** [review]

**Pull request merged**
